### ISSUE TITLE
Unable to set UID

### ISSUE THREAD

**Issue by Jinn4400** [yandex-cloud/geesefs#73]
**geesefs version**: 0.35.0
I try to mount with **--uid=1000** (user with UID=1000 exist), but nothing works.
`ls -l /mnt/
ls: cannot access /mnt/test: Permission denied
total 0
d????????? ? ? ? ?            ? test`
Without **--uid** flag working.

**Comment by vitalif** [comment]
Do you mount it under root and check under root (not user 1000)?

Either check it under user 1000.

Or add -o allow_root to allow root to access mount point. Or -o allow_other to allow everyone to access it. This is FUSE behaviour, by default it only allows access to the root directory of the mount for the mount owner.

**Comment by vitalif** [comment]
I'm closing this, reopen if there's some other problem except what I said

**Comment by vitalif** [comment]
Please add -o allow_other and recheck
This is FUSE behaviour as I said above

**Comment by redtex** [comment]
![image](https://github.com/user-attachments/assets/37f456fc-6445-421c-a2a4-eaf35923a3d4)
it's definitely bug
with ```--uid``` option there is unreadable mount as mentioned before
with mount option ```-o allow_other``` ordinary user can't write to mountpoint

**Comment by vitalif** [comment]
This is really FUSE behaviour
Take a look at fuse_allow_current_process() https://github.com/torvalds/linux/blob/master/fs/fuse/dir.c#L1441
Then at fuse_permissible_uidgid() https://github.com/torvalds/linux/blob/master/fs/fuse/dir.c#L1420
It checks BOTH owner uid and gid when accessing the FS. That's why you can't access the FS with just the --uid option.
A workaround is to also add `-o group_id=1000`.
In the next release `--gid 1000` will also work - it was meant to already work like this, but `setgid` value was not passed as FUSE `group_id` option, so it didn't. I just committed a fix for it in master.

**Comment by redtex** [comment]
Nice !!!
It works !
And as feature request, it's would be logical, to enable option 'allow_other' when options 'gid' and 'uid' present in geesefs call
